spring:
  application:
    name: cafocolo-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cafocolo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080
